language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: cl6XZh0byC1zJRG2qezyMyolyVzr7FHHMM0g0uwomT9pXYxNrpzogXL3TUmVz/Il+hRRf6Vv0T+j5hFtRMclKGkEdt+d+C4KSvHsLWFs4CHDTagWPCrK0GO9MLvdVzEX2zFiQlT1S2SLKLl61wsmeBbQmVcgO5we5W+JUSTsLH5li9ipl8+vMv2n2ldrp0gQERGdMtSlotxbacppQ3teyP9v2r414WBhevU/fe50iiFPTgNFUhr1UgkP40JEpTEUy2v3MJPBME5jLJVXOGRLdhWb8NwM/hthYkHz5Fv3eSGr+TMtEgTxcZkUuyMijzJOemKj1B9/Kp2SBNIgS3JXHgkNMZnvJxKmbA0XGKB8WSnmGIUc9dnTG7WT3bw+tPAMWXh/g73cf4lvWes4Sr3AomtHDVgcKM4p315lJY+n9b9pAUheXpFSJQ/8bNxCE6Hf8YI2knJVqSok0MW4N0l4Bjdpc5McOZzcNTF7jXxyRxW9mTWenh5pehuyD2NWltHdbEzylnQqIILh5f/nkzcaOuUJBr//7PT//wHOoF9m5/10Mg4cxkmy3QQhvwh7DnbnZXphd+4qYxfZkrG/VotxBZxZpG0evzqA9OPs5TE31VLQHGloHXFm47vvZNhluWn+fUGYCfK7aSoLsCAbXfL0nIEaVMRLrOl5g4eE1DS5HxE=
  app: joseph-mongoose-travisci-integration
  on:
    repo: thinkful-ei21/joseph-mongoose-travisci-integration
    branch: feature/with-tests
