language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: tUwVwR78Edh6EMy0gBp+E5SqP/fvhMHTHd4B2KWyR7VDCZsMCuVPrV3VrVqLqjryY9XvcoRlERq1yN3Y+RPwjS/uQWrWwkel1H2NLKtoBHNmcabwVBdwI/7cLXtDF9abjN2qyQS1tG/3ycGNM/nIPQHTl//5kQmIrCmH1Y7kMG3mNC2mExPXc7DGS+tbER3AmaJFByuMbs8f0E5Wz++uvTR3+TVswGLf/TgpEmIpwd39ouZmDQX5uD1yYMQqkszXRARJFt8Bo/lgesDIYcg/ADKAuHzRyXXooarjQpciYOKQKy1iNGizU8fASFSSb5PUbK74WEecrkmPmr5czl0aNlaesucEzP3+bAMD2fsLHZZQFs/LoTtdIGpqVh3+uamxFJsZBF8DZCOtS4HAGqLFvafZjZwkskxPXDLjEHBHWk6ufdIIFjBksyRBo7VkFTGtRajJ2oipGX20Zd+/yYV1E+P7sT2mMoB+apfbBOXHaovJNjw69voRXh8NVW60oPe0j7QMKf1Y/WlkRbkwK7GFi76N938rjvwH3KUpPuN8ijvf9zhHTBhcOK2ZxpC3DdFUHeNFvPT5P2ys3tBDO19M2ArmMxZ3buFwYqu6khsJdHiDvyy0dHR0eOkHJQkJiblCq6RQZ049ZfgwgI9CpL2cD5wNN72trm3WeyguwUC2j/I=
  app: shrouded-shore-64155
  on:
    repo: thinkful-ei21/joseph-mongoose-travisci-integration
    branch: feature/with-tests
